[workspace]
members = [
    "bin/helix-user-api",
    "bin/helix-user-grpc",
    "helix-user-domain",
    "storage/helix-pg-db-user-storage"
]

##DEFAULT RUNNING BIN
default-members=["bin/helix-user-api"]


##__FIX FOR ARM COMPILATION SINCE RUST 1.38
[profile.release]
codegen-units = 1