[package]
name = "helix-user-api"
version = "1.0.0"
authors = ["SlackMagiC <laurent.pietrzyk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
##API MANAGEMENT
actix-web = "3.3.2"
actix-rt = "1.1.1"
actix-service = "1.0.6"
actix-files = "0.5.0"
futures = "0.3.13"

##VARIABLES & LOGS
env_logger = "*"
dotenv = "0.15.0"

##SERIALIZATION TO JSON
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
json = "*"

##DATA UTILS => UTC Date, UUID generation
uuid = { version = "0.8", features = ["v5", "serde"]}
chrono = { version = "^0.4", features = ["serde"] }

##DOMAIN
helix-user-domain = { path = "../../helix-user-domain" }
helix-pg-db-user-storage = { path = "../../storage/helix-pg-db-user-storage" }
helix-auth-lib = {git = "https://github.com/slackmagic/helix-shared-lib", branch = "master"}
helix-config-lib = {git = "https://github.com/slackmagic/helix-shared-lib", branch = "master"}

[build-dependencies]
##VERSION
void-budi = {git = "https://github.com/slackmagic/void-budi", branch = "master"}